name = "todomvc"

packages = [
  # build tools
  ### Rust
  "todomvc.nix.pkgs.rust",
  ### Haskell
  "haskellPackages.ghc",
  ### Others
  "binutils",
  "gcc",

  # backend
  "todomvc.nix.backend",

  # database
  "sqitchPg",
  "postgresql",
  "moreutils",

]

[env]
PGHOST="localhost"
PGPORT="5432"
PGDATABASE="test_db"
PGUSER="test_user"
PGPASSWORD="test_pass"
